In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("./texts.csv")

In [3]:
label2id = {
    "O": 0,
    "B-NAME": 1,
    "I-NAME": 2,
    "B-GENDER": 3,
    "B-DOB": 4,
    "I-DOB": 5,
    "B-NATIONALITY": 6,
    "I-NATIONALITY": 7,
    "B-CITY": 8,
    "I-CITY": 9,
    "B-EMAIL": 10,
    "B-PHONE": 11,
    "I-PHONE": 12,
    "B-AADHAR": 13,
    "I-AADHAR": 14,
    "B-PAN": 15,
    "B-VOTER": 16,
    "B-PASSPORT": 17,
    "I-PASSPORT": 18,
    "B-LICENSE": 19,
    "I-LICENSE": 20,
    "B-ACCOUNTNUMBER": 21,
    "I-ACCOUNTNUMBER": 22,
    "B-BANKIFSC": 23,
    "B-CARDNUMBER": 24,
    "B-CVV": 25,
    "B-IP": 26,
}

In [4]:
def convert_label_to_id(tags):
    return [label2id.get(tag, 0) for tag in tags]

In [5]:
# Apply the conversion
data['ner_tags'] = data['ner_tags'].apply(eval)  # If needed
data['ner_tags_numeric'] = data['ner_tags'].apply(convert_label_to_id)

# Replace original column
data['ner_tags'] = data['ner_tags_numeric']
del data['ner_tags_numeric']

In [6]:
data

,text,tokens,ner_tags
0,"The passport application of Ms.Anjali Sharma, ...","['The', 'passport', 'application', 'of', 'Ms.'...","[0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 4, 0, 0, 0, 0, ..."
1,"The Indian national, residing in Abadgarh, who...","['The', 'Indian', 'national', ',', 'residing',...","[0, 6, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 4, 0, ..."
2,"The passport holder, Sharath Chandran, a male ...","['The', 'passport', 'holder', ',', 'Sharath', ...","[0, 0, 0, 0, 1, 2, 0, 0, 3, 0, 0, 4, 0, 0, 0, ..."
3,"The Indian citizen, whose passport number is R...","['The', 'Indian', 'citizen', ',', 'whose', 'pa...","[0, 6, 0, 0, 0, 0, 0, 0, 17, 18, 0, 0, 0, 8, 0..."
4,"Indian citizen Amit, born on 13/11/1961, havin...","['Indian', 'citizen', 'Amit', ',', 'born', 'on...","[6, 0, 1, 0, 0, 0, 4, 0, 0, 0, 0, 16, 0, 0, 10..."
...,...,...,...
968,"The applicant, Mr. Rohan Sharma, a male born o...","['The', 'applicant,', 'Mr.', 'Rohan', 'Sharma,...","[0, 0, 0, 1, 2, 0, 3, 0, 0, 4, 0, 0, 0, 13, 0,..."
969,"Indian national, Ms. Priya Patel, residing in ...","['Indian', 'national,', 'Ms.', 'Priya', 'Patel...","[6, 7, 0, 1, 2, 0, 0, 8, 0, 0, 0, 16, 0, 17, 0..."
970,"The Indian national, Mr. sourav sumit, residin...","['The', 'Indian', 'national', ',', 'Mr.', 'sou...","[0, 6, 0, 0, 0, 1, 2, 0, 0, 0, 8, 0, 0, 0, 17,..."
971,"Chain Singh @ Ravi, born on 07/09/2023, holds ...","['Chain', 'Singh', '@', 'Ravi', ',', 'born', '...","[1, 2, 0, 2, 0, 0, 0, 4, 0, 0, 0, 0, 16, 0, 0,..."
972,"Mr. Barjraj Shivani, an Indian national born o...","['Mr.', 'Barjraj', 'Shivani', ',', 'an', 'Indi...","[0, 1, 2, 0, 0, 6, 0, 0, 0, 4, 0, 0, 0, 0, 0, ..."

In [7]:
data = data.sample(frac=1, random_state=42).reset_index(drop=True)

In [8]:
data

,text,tokens,ner_tags
0,"Bhola Sarkar, a male Indian national residing ...","['Bhola', 'Sarkar', ',', 'a', 'male', 'Indian'...","[1, 2, 0, 0, 3, 6, 7, 0, 0, 8, 0, 0, 10, 0, 0,..."
1,The application for driving license DL68 20095...,"['The', 'application', 'for', 'driving', 'lice...","[0, 0, 0, 0, 0, 19, 20, 0, 0, 0, 1, 2, 0, 0, 0..."
2,"Male resident Raghunandan Das, residing in Agr...","['Male', 'resident', 'Raghunandan', 'Das', ','...","[3, 0, 1, 2, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 13,..."
3,"Ms. Priya Sharma, residing in Alu city, posses...","['Ms.', 'Priya', 'Sharma', ',', 'residing', 'i...","[0, 1, 2, 0, 0, 0, 8, 0, 0, 0, 0, 0, 13, 0, 0,..."
4,"Hemant, a male born on 26-06-1963, possesses P...","['Hemant', ',', 'a', 'male', 'born', 'on', '26...","[1, 0, 0, 3, 0, 0, 4, 0, 0, 0, 15, 0, 0, 0, 0,..."
...,...,...,...
968,"Rajesh Kumar, a Male resident of Bangalore, ho...","['Rajesh', 'Kumar', ',', 'a', 'Male', 'residen...","[1, 2, 0, 0, 3, 0, 0, 8, 0, 0, 0, 0, 13, 0, 0,..."
969,"The Ajitpura resident, a male, Mr.Barjraj Shiv...","['The', 'Ajitpura', 'resident,', 'a', 'male,',...","[0, 8, 0, 0, 3, 0, 1, 2, 0, 0, 4, 0, 0, 0, 0, ..."
970,"Antarasante resident, Mr. Rohan Sharma, born o...","['Antarasante', 'resident,', 'Mr.', 'Rohan', '...","[8, 0, 0, 1, 2, 0, 0, 4, 0, 0, 0, 13, 0, 15, 0..."
971,"A male, Avdhesh, holding passport number C79 6...","['A', 'male', ',', 'Avdhesh', ',', 'holding', ...","[0, 3, 0, 1, 0, 0, 0, 0, 17, 18, 0, 0, 0, 0, 0..."
972,"Shelender Yadav, an Indian national, uses mf58...","['Shelender', 'Yadav', ',', 'an', 'Indian', 'n...","[1, 2, 0, 0, 6, 0, 0, 0, 10, 0, 0, 0, 0, 13, 0..."

## Defining Dataset Features and Splits for Dataset

In [10]:
from datasets import Dataset, DatasetDict, Features, ClassLabel, Sequence, Value, DatasetInfo

# Define your labels
label_names = ["O", "B-NAME", "I-NAME", "B-GENDER", "B-DOB", "I-DOB", "B-NATIONALITY", "I-NATIONALITY", "B-CITY", "I-CITY", "B-EMAIL", "B-PHONE", "I-PHONE", "B-AADHAR", "I-AADHAR", "B-PAN", "B-VOTER", "B-PASSPORT", "I-PASSPORT", "B-LICENSE", "I-LICENSE", "B-ACCOUNTNUMBER", "I-ACCOUNTNUMBER", "B-BANKIFSC", "B-CARDNUMBER", "B-CVV", "B-IP"]


# Define features
features = Features({
    'text': Value('string'),
    'tokens': Sequence(Value('string')),
    'ner_tags': Sequence(ClassLabel(num_classes=len(label_names), names=label_names))
})

# Add info about the dataset
description = """This dataset contains annotated sentences from the personal information.
It includes annotations for name, gender, number, account number.

Tags:
- "O": "Non-entity tokens"
- "B-NAME": "Start of indian name - (e.g. Amit, Rajesh, Ankit, Brajraj, Rekha, Arshad, Niraj, Jyoti)",
- "I-NAME": "Continuation of names - (e.g Solanki, Kalathia, Singh)",
- "B-GENDER": "Value of gender - (e.g. Male, Female, Transgender)",
- "B-DOB": "Start of Birthdate - (e.g. March 18 2003, 02/01/2004, 08-06-1998)",
- "I-DOB": "Continuation of Birthdate",
- "B-NATIONALITY": "Start of Nationality - (e.g. Indian, American, Chinese, Japanese)",
- "I-NATIONALITY": "Continuation of Nationality",
- "B-CITY": "Start of city name - (e.g. Jodhpur, Bangalore, Hyderabad, Mumbai, Pune)",
- "I-CITY": "Continuation of city name",
- "B-EMAIL": "Start of email address - (e.g., indianindian23@gmail.com, barjrajshivani776@gmail.com)",
- "B-PHONE": "Start of phone number - (e.g. 874 892 4670, 91 7140728911, +9180679 73921, 75081 18639)",
- "I-PHONE": "Continuation of phone number",
- "B-AADHAR": "Start of aadhar card number - (e.g. 257574488836, 800476797877)",
- "I-AADHAR": "Continuation of aadhar card number",
- "B-PAN": "Start of pan number - (e.g., XJVMV8282Y, CKNJX9036X, WZIRX3768L)",
- "B-VOTER": "Start of voter identitiy number - (e.g., KGI6158551, ILX3627901)",
- "B-PASSPORT": "Start of passport number - (e.g., K4190715, S1721121, G48 38859)",
- "I-PASSPORT": "Continuation of passport number",
- "B-LICENSE": "Start of driving license number - (e.g., TN87 20075880927, JK01 20104637542, TR-7120118774157)",
- "I-LICENSE": "Continuation of driving license number",
- "B-ACCOUNTNUMBER": "Start of bank account number - (e.g., 11389823690, 71717839372, 78339305069)",
- "I-ACCOUNTNUMBER": "Continuation of bank account number",
- "B-BANKIFSC": "Start of bank ifsc code - (e.g., IDIB0755055, ICIC0313449, SBIN0547870)",
- "B-CARDNUMBER": "Start of atm card number - (e.g., 40265307837299051, 50786592905011426, 40001623133171904)",
- "B-CVV": "Start of cvv code of atm card - (e.g., 837, 318, 635)",
- "B-IP": "Start of ip address - (e.g., 46.81.232.82, 222.15.54.4, 167.77.106.135)",

Note: This dataset is created using gemini 1.5 and is only for research and education purposes. For production, it is highly recommended to use human-annotated data.
"""

# Create a DatasetInfo object
my_dataset_info = DatasetInfo(
    description=description,
    dataset_name="Personal Information Dataset",
    features=features,
)

# Create dataset with features
dataset = Dataset.from_dict(
    {
        'text': data['text'].tolist(),
        'tokens': data['tokens'].apply(eval).tolist(),
        'ner_tags': data['ner_tags'].tolist()
    },
    info=my_dataset_info
)

# Create splits
dataset = dataset.train_test_split(test_size=0.2, seed=42)
test_valid = dataset['test'].train_test_split(test_size=0.5, seed=42)

# Create final dataset dictionary
hf_dataset = DatasetDict({
    'train': dataset['train'],
    'validation': test_valid['train'],
    'test': test_valid['test']
})

# Print to verify
print("Features:", hf_dataset['train'].features)
# print("\nDescription:", hf_dataset.info.description)

Features: {'text': Value(dtype='string', id=None), 'tokens': Sequence(feature=Value(dtype='string', id=None), length=-1, id=None), 'ner_tags': Sequence(feature=ClassLabel(names=['O', 'B-NAME', 'I-NAME', 'B-GENDER', 'B-DOB', 'I-DOB', 'B-NATIONALITY', 'I-NATIONALITY', 'B-CITY', 'I-CITY', 'B-EMAIL', 'B-PHONE', 'I-PHONE', 'B-AADHAR', 'I-AADHAR', 'B-PAN', 'B-VOTER', 'B-PASSPORT', 'I-PASSPORT', 'B-LICENSE', 'I-LICENSE', 'B-ACCOUNTNUMBER', 'I-ACCOUNTNUMBER', 'B-BANKIFSC', 'B-CARDNUMBER', 'B-CVV', 'B-IP'], id=None), length=-1, id=None)}

In [11]:
hf_dataset["train"][0]

{'text': 'The bank account holder, Ms. Priya Sharma, possesses a driving license with number ML98 20007299984, her bank uses the IFSC code PNB0487059, and her ATM card has CVV 349; her last known IP address was 112.249.241.110.',
 'tokens': ['The',
  'bank',
  'account',
  'holder',
  ',',
  'Ms.',
  'Priya',
  'Sharma',
  ',',
  'possesses',
  'a',
  'driving',
  'license',
  'with',
  'number',
  'ML98',
  '20007299984',
  ',',
  'her',
  'bank',
  'uses',
  'the',
  'IFSC',
  'code',
  'PNB0487059',
  ',',
  'and',
  'her',
  'ATM',
  'card',
  'has',
  'CVV',
  '349',
  ';',
  'her',
  'last',
  'known',
  'IP',
  'address',
  'was',
  '112.249.241.110'],
 'ner_tags': [0,
  0,
  0,
  0,
  0,
  0,
  1,
  2,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  19,
  20,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  23,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  25,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  26]}

In [12]:
hf_dataset["train"].features["ner_tags"]

Sequence(feature=ClassLabel(names=['O', 'B-NAME', 'I-NAME', 'B-GENDER', 'B-DOB', 'I-DOB', 'B-NATIONALITY', 'I-NATIONALITY', 'B-CITY', 'I-CITY', 'B-EMAIL', 'B-PHONE', 'I-PHONE', 'B-AADHAR', 'I-AADHAR', 'B-PAN', 'B-VOTER', 'B-PASSPORT', 'I-PASSPORT', 'B-LICENSE', 'I-LICENSE', 'B-ACCOUNTNUMBER', 'I-ACCOUNTNUMBER', 'B-BANKIFSC', 'B-CARDNUMBER', 'B-CVV', 'B-IP'], id=None), length=-1, id=None)

In [13]:
print(hf_dataset['train'].description)

This dataset contains annotated sentences from the personal information.
It includes annotations for name, gender, number, account number.

Tags:
- "O": "Non-entity tokens"
- "B-NAME": "Start of indian name - (e.g. Amit, Rajesh, Ankit, Brajraj, Rekha, Arshad, Niraj, Jyoti)",
- "I-NAME": "Continuation of names - (e.g Solanki, Kalathia, Singh)",
- "B-GENDER": "Value of gender - (e.g. Male, Female, Transgender)",
- "B-DOB": "Start of Birthdate - (e.g. March 18 2003, 02/01/2004, 08-06-1998)",
- "I-DOB": "Continuation of Birthdate",
- "B-NATIONALITY": "Start of Nationality - (e.g. Indian, American, Chinese, Japanese)",
- "I-NATIONALITY": "Continuation of Nationality",
- "B-CITY": "Start of city name - (e.g. Jodhpur, Bangalore, Hyderabad, Mumbai, Pune)",
- "I-CITY": "Continuation of city name",
- "B-EMAIL": "Start of email address - (e.g., indianindian23@gmail.com, barjrajshivani776@gmail.com)",
- "B-PHONE": "Start of phone number - (e.g. 874 892 4670, 91 7140728911, +9180679 73921, 75081 18639)",
- "I-PHONE": "Continuation of phone number",
- "B-AADHAR": "Start of aadhar card number - (e.g. 257574488836, 800476797877)",
- "I-AADHAR": "Continuation of aadhar card number",
- "B-PAN": "Start of pan number - (e.g., XJVMV8282Y, CKNJX9036X, WZIRX3768L)",
- "B-VOTER": "Start of voter identitiy number - (e.g., KGI6158551, ILX3627901)",
- "B-PASSPORT": "Start of passport number - (e.g., K4190715, S1721121, G48 38859)",
- "I-PASSPORT": "Continuation of passport number",
- "B-LICENSE": "Start of driving license number - (e.g., TN87 20075880927, JK01 20104637542, TR-7120118774157)",
- "I-LICENSE": "Continuation of driving license number",
- "B-ACCOUNTNUMBER": "Start of bank account number - (e.g., 11389823690, 71717839372, 78339305069)",
- "I-ACCOUNTNUMBER": "Continuation of bank account number",
- "B-BANKIFSC": "Start of bank ifsc code - (e.g., IDIB0755055, ICIC0313449, SBIN0547870)",
- "B-CARDNUMBER": "Start of atm card number - (e.g., 40265307837299051, 50786592905011426, 40001623133171904)",
- "B-CVV": "Start of cvv code of atm card - (e.g., 837, 318, 635)",
- "B-IP": "Start of ip address - (e.g., 46.81.232.82, 222.15.54.4, 167.77.106.135)",

Note: This dataset is created using gemini 1.5 and is only for research and education purposes. For production, it is highly recommended to use human-annotated data.

In [14]:
hf_dataset

DatasetDict({
    train: Dataset({
        features: ['text', 'tokens', 'ner_tags'],
        num_rows: 778
    })
    validation: Dataset({
        features: ['text', 'tokens', 'ner_tags'],
        num_rows: 97
    })
    test: Dataset({
        features: ['text', 'tokens', 'ner_tags'],
        num_rows: 98
    })
})

## Saving the dataset

In [15]:
# Suppose you have a Dataset or DatasetDict called 'hf_dataset'
hf_dataset.save_to_disk("pii_ner_dataset")

Saving the dataset (0/1 shards):   0%|          | 0/778 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/97 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/98 [00:00<?, ? examples/s]